import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {writeFileSync,readFileSync,readdirSync,existsSync} from 'node:fs';
import {Client} from 'pg';
import assert from 'node:assert/strict';
import {getPrismaClient,resetClientPool} from './src/database/prisma';
import {getAuth} from './src/lib/auth';
import {initOwner} from './src/services/ownerInit';
import {FILE_HEADERS} from './src/adapters/contracts';
import {signDownload} from './src/storage';
const T='/tmp/aiea-g2r2-9hnwja_c',B=process.env.BETTER_AUTH_URL!;
const results:any[]=[];const db=getPrismaClient(),auth=getAuth();const pg=new Client({connectionString:process.env.DATABASE_URL});
const password='Review-'+randomBytes(16).toString('hex');
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
async function check(name:string,expected:any,fn:()=>Promise<any>){let actual:any;try{actual=await fn();assert.deepEqual(actual,expected);results.push({name,expected,actual,status:'PASS'});}catch(e:any){results.push({name,expected,actual,status:'FAIL',error:e.message?.slice(0,900)});}console.log(name,results.at(-1).status);writeFileSync(T+'/evidence/http-assertions.json',JSON.stringify(results,null,2));}
async function request(path:string,cookie:string,method='GET',body?:any,key?:string){const headers:any={cookie,origin:B};if(key)headers['idempotency-key']=key;let payload:any;if(body instanceof FormData)payload=body;else if(body!==undefined){headers['content-type']='application/json';payload=JSON.stringify(body);}const r=await fetch(B+path,{method,headers,body:payload,signal:AbortSignal.timeout(15000)});const t=await r.text();let b:any;try{b=JSON.parse(t)}catch{b={text:t}}return {status:r.status,body:b,headers:Object.fromEntries(r.headers)};}
async function actor(role:string,orgId?:string){const email=`r2-${role}-${randomUUID()}@example.test`;let userId:string;if(!orgId){const r=await initOwner(db,{orgName:email,email,displayName:role,demoMode:false,password},async(email,password,name)=>({authUserId:(await auth.api.signUpEmail({body:{email,password,name}})).user.id}));orgId=r.orgId;userId=r.userId;}else{const u=await auth.api.signUpEmail({body:{email,password,name:role}});const d=await db.user.create({data:{authUserId:u.user.id,email,displayName:role}});userId=d.id;await db.membership.create({data:{orgId,userId,role:role as any}});}const r=await auth.api.signInEmail({body:{email,password},asResponse:true});assert.equal(r.status,200);return {orgId:orgId!,userId,cookie:r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; '),email};}
function csv(kind:string,id:string){const rows:any={products:['G2-STORE','2026-09-11T00:00:00Z',id,'Product','','active',id,'SKU-'+id,'Name','','active'],orders:['G2-STORE','2026-09-11T00:00:00Z',id,'paid','2026-09-01T00:00:00Z','2026-09-01T01:00:00Z','CNY','1'],customer_messages:['G2-STORE','2026-09-11T00:00:00Z',id,id,'2026-09-01T01:00:00Z','','Synthetic message','','platform_chat','en']};return FILE_HEADERS[kind as keyof typeof FILE_HEADERS].join(',')+'\n'+rows[kind].join(',');}
async function main(){await pg.connect();const owner=await actor('owner'),admin=await actor('admin',owner.orgId),op=await actor('operator',owner.orgId),cs=await actor('customer_service',owner.orgId),other=await actor('owner');
const s=await request('/api/v1/stores',owner.cookie,'POST',{name:'R2 Store',external_store_id:'G2-STORE',platform:'amazon',currency:'CNY',timezone:'Asia/Shanghai'});assert.equal(s.status,201);const storeId=s.body.data.id;
const ds=await request('/api/v1/data-sources',owner.cookie,'POST',{store_id:storeId,name:'R2 source',adapter_kind:'csv',source_namespace:'r2_source'});assert.equal(ds.status,201);const sourceId=ds.body.data.id;
writeFileSync(T+'/actors-private.json',JSON.stringify({owner,admin,op,cs,other,storeId,sourceId}),{mode:0o600});
async function upload(a:any,kind:string,text:string|Buffer,key?:string,filename='test.csv'){await db.authRateLimit.deleteMany({where:{keyHash:hash(`upload:${a.orgId}:${a.userId}`)}}).catch(()=>{});const f=new FormData();f.set('store_id',storeId);f.set('data_source_id',sourceId);f.set('entity_type',kind);f.set('file',new File([text],filename,{type:'text/csv'}));return request('/api/v1/imports',a.cookie,'POST',f,key);}
async function freshUpload(a:any,kind:string,id:string,key?:string){return upload(a,kind,csv(kind,id),key)}
let normal:any;await check('M01 normal entity_type and response fields',{status:201,bytes:true,filename:'test.csv',rows:1},async()=>{normal=await freshUpload(owner,'products','normal');return {status:normal.status,bytes:normal.body.data?.bytes===Buffer.byteLength(csv('products','normal')),filename:normal.body.data?.filename,rows:normal.body.data?.row_count}});
assert.ok(normal.body.data?.id);const taskId=normal.body.data.id;
await check('H07 sequential content reuse',{status:200,same:true},async()=>{const r=await freshUpload(owner,'products','normal');return {status:r.status,same:r.body.data?.id===taskId}});
const msg=await freshUpload(cs,'customer_messages','cs-normal'),ord=await freshUpload(op,'orders','op-normal');assert.equal(msg.status,201);assert.equal(ord.status,201);
await check('H05 current role query matrix',[200,200,403,404],async()=>[(await request('/api/v1/imports/'+msg.body.data.id,cs.cookie)).status,(await request('/api/v1/imports/'+ord.body.data.id,op.cookie)).status,(await request('/api/v1/imports/'+ord.body.data.id,cs.cookie)).status,(await request('/api/v1/imports/'+taskId,other.cookie)).status]);
const task=await db.importTask.findUniqueOrThrow({where:{id:msg.body.data.id}}),sig=signDownload(task.rawObjectKey),fp=`/api/v1/imports/${task.id}/file`;
await check('H05 L02 signed download and isolation',[403,403,200,true,404,true],async()=>{const a=await request(fp,cs.cookie),e=signDownload(task.rawObjectKey,-1),b=await request(fp+`?expires=${e.expiresAt}&signature=${e.signature}`,cs.cookie),c=await request(fp+`?expires=${sig.expiresAt}&signature=${sig.signature}`,cs.cookie),d=await request(fp+`?expires=${sig.expiresAt}&signature=${sig.signature}`,other.cookie);return[a.status,b.status,c.status,c.body.text===csv('customer_messages','cs-normal'),d.status,Math.abs(sig.expiresAt-Date.now()-300000)<10000]});
for(const v of [1n,2n])for(const [kind,count] of [['orders',v===1n?100n:120n],['customer_messages',v===1n?3n:4n]] as const)await db.dataCoverage.create({data:{orgId:owner.orgId,storeId,dataSourceId:sourceId,sourceKind:kind,channel:'default_channel',coverageDate:new Date('2026-09-01Z'),status:'complete',explicitZero:false,recordCount:count,datasetVersion:v,importTaskId:taskId}});
await db.store.update({where:{id:storeId},data:{datasetVersion:2n}});
await check('H01 effective coverage role projection',[[124,2],[4,1]],async()=>{const out=[];for(const a of[owner,cs]){const r=await request('/api/v1/data-sources?store_id='+storeId+'&from=2026-09-01&to=2026-09-02',a.cookie);const c=r.body.data.items[0].coverage[0];out.push([c.record_count,c.source_kinds]);}return out});
await check('H01 date validation and exclusive end',[0,422,422,422],async()=>{const path='/api/v1/data-sources?store_id='+storeId;return [(await request(path+'&from=2026-08-31&to=2026-09-01',owner.cookie)).body.data.items[0].coverage.length,(await request(path+'&from=garbage',owner.cookie)).status,(await request(path+'&from=2026-02-30',owner.cookie)).status,(await request(path+'&from=2026-01-01&to=2026-09-01',owner.cookie)).status]});
await check('H02 row lock concurrent CAS',[200,409,2,1],async()=>{const lock=new Client({connectionString:process.env.DATABASE_URL});await lock.connect();await lock.query('BEGIN');await lock.query('SELECT id FROM store WHERE id=$1 FOR UPDATE',[storeId]);const p=[request('/api/v1/stores/'+storeId,owner.cookie,'PATCH',{name:'CAS one',expected_version:1}),request('/api/v1/stores/'+storeId,admin.cookie,'PATCH',{name:'CAS two',expected_version:1})];let n=0;for(let i=0;i<100;i++){n=Number((await pg.query("SELECT count(*) n FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND query LIKE '%UPDATE%store%' ")).rows[0].n);if(n>=2)break;await new Promise(r=>setTimeout(r,20));}await lock.query('COMMIT');await lock.end();assert.ok(n>=2);const rs=await Promise.all(p);return[...rs.map(r=>r.status).sort(),(await db.store.findUniqueOrThrow({where:{id:storeId}})).rowVersion,await db.auditLog.count({where:{entityId:storeId,action:'store_update'}})]});
await check('M02 concurrent name uniqueness',[201,409,409],async()=>{const rs=await Promise.all(Array.from({length:3},(_,i)=>request('/api/v1/stores',owner.cookie,'POST',{name:'same parallel',external_store_id:'PAR-'+i,platform:'manual',currency:'CNY',timezone:'UTC'})));return rs.map(r=>r.status).sort()});
await check('H07 concurrent same bytes one task',{statuses:[200,200,200,201],ids:1,rows:1},async()=>{const text=csv('products','parallel-content');const rs=await Promise.all(Array.from({length:4},()=>upload(admin,'products',text)));return{statuses:rs.map(r=>r.status).sort(),ids:new Set(rs.map(r=>r.body.data?.id)).size,rows:await db.importTask.count({where:{storeId,fileSha256:hash(text)}})}});
await check('H07 ordinary HTTP replay and conflict',[201,201,true,409],async()=>{const key='r2-key-normal',a=await freshUpload(owner,'products','http-a',key),b=await freshUpload(owner,'products','http-a',key),c=await freshUpload(owner,'products','http-b',key);return[a.status,b.status,a.body.data?.id===b.body.data?.id,c.status]});
await check('H07 reusable content binds a new HTTP key',[200,200,409,1],async()=>{const base=csv('products','normal');const a=await upload(admin,'products',base,'r2-reuse-key'),b=await upload(admin,'products',base,'r2-reuse-key'),c=await freshUpload(admin,'products','reuse-changed','r2-reuse-key');return[a.status,b.status,c.status,await db.httpIdempotency.count({where:{orgId:admin.orgId,userId:admin.userId,requestKey:hash(`${admin.orgId}:${admin.userId}:/api/v1/imports:r2-reuse-key`).slice(0,48)}})]});
await check('H07 key isolation across users',[201,201],async()=>[(await freshUpload(owner,'products','user-a','r2-shared-users')).status,(await freshUpload(admin,'products','user-b','r2-shared-users')).status]);
await check('H07 expiration allows a new request after 24h',[201,201],async()=>{const key='r2-expired-key',a=await freshUpload(owner,'products','expires-a',key);await db.httpIdempotency.updateMany({where:{requestKey:hash(`${owner.orgId}:${owner.userId}:/api/v1/imports:${key}`).slice(0,48)},data:{createdAt:new Date(Date.now()-25*3600000)}});const b=await freshUpload(owner,'products','expires-b',key);return[a.status,b.status]});
await check('H08 HTTP ledger failure cannot report unprotected success',true,async()=>{await pg.query("ALTER TABLE http_idempotency ADD CONSTRAINT reviewer_fail_ledger CHECK(false) NOT VALID");let a:any;try{a=await freshUpload(op,'products','ledger-fail','r2-ledger-key')}finally{await pg.query('ALTER TABLE http_idempotency DROP CONSTRAINT reviewer_fail_ledger')}return a.status>=500 || await db.httpIdempotency.count({where:{orgId:op.orgId,userId:op.userId}})>0});
const tmp=()=>existsSync(T+'/private/tmp')?readdirSync(T+'/private/tmp').filter(x=>x.endsWith('.csv')):[];
await check('H06 rejected type cleans spool',{status:415,newTempFiles:0},async()=>{const before=tmp();const r=await upload(admin,'products',csv('products','xlsx'),undefined,'x.xlsx');return{status:r.status,newTempFiles:tmp().filter(x=>!before.includes(x)).length}});
await check('H06 forbidden role cleans spool',{status:403,newTempFiles:0},async()=>{const before=tmp();const r=await freshUpload(cs,'orders','forbidden');return{status:r.status,newTempFiles:tmp().filter(x=>!before.includes(x)).length}});
await check('M03 strict UTF8',[422,'INVALID_ENCODING'],async()=>{const r=await upload(admin,'products',Buffer.concat([Buffer.from('x\n'),Buffer.from([0x80])]));return[r.status,r.body.error?.code]});
await check('H06 quoted newline logical count',[201,50001],async()=>{const text=FILE_HEADERS.customer_messages.join(',')+'\n'+Array(50001).fill('G2-STORE,2026-09-11T00:00:00Z,MSG,C,2026-09-01T00:00:00Z,,"first\nsecond",,chat,en').join('\n');const r=await upload(admin,'customer_messages',text);return[r.status,r.body.data?.row_count]});
await check('H06 blank-line CSV cannot bypass 100000 rows',[422,'TOO_MANY_ROWS'],async()=>{const row=csv('products','blank-bypass').split('\n')[1];const text=FILE_HEADERS.products.join(',')+'\n\n'+Array(100001).fill(row).join('\n');const r=await upload(admin,'products',text);return[r.status,r.body.error?.code??r.body.data?.row_count]});
await check('H05 revoked session query and download',[403,403],async()=>{await db.membership.updateMany({where:{orgId:cs.orgId,userId:cs.userId},data:{status:'disabled'}});const rs=[(await request('/api/v1/imports/'+task.id,cs.cookie)).status,(await request(fp+`?expires=${sig.expiresAt}&signature=${sig.signature}`,cs.cookie)).status];await db.membership.updateMany({where:{orgId:cs.orgId,userId:cs.userId},data:{status:'active'}});return rs});
await check('M03 default rate bucket enforces 20 per minute',true,async()=>{await db.authRateLimit.deleteMany();const f=()=>{const x=new FormData();x.set('store_id',storeId);x.set('data_source_id',sourceId);x.set('entity_type','products');x.set('file',new File([csv('products','ratetest')],'r.csv'));return x};const rs=[];for(let i=0;i<21;i++)rs.push(await request('/api/v1/imports',op.cookie,'POST',f()));writeFileSync(T+'/evidence/rate-responses.json',JSON.stringify(rs.map(x=>({status:x.status,body:x.body,headers:x.headers})),null,2));return rs.slice(0,20).every(x=>[200,201].includes(x.status))&&rs[20].status===429});
await db.$disconnect();await resetClientPool();await pg.end();process.exit(results.some(x=>x.status==='FAIL')?1:0);
}
main().catch(e=>{console.error(e);process.exit(2)});
