import{randomUUID,createHash}from'node:crypto';import{readFileSync,writeFileSync,openSync,mkdirSync}from'node:fs';import{spawn}from'node:child_process';import{Readable}from'node:stream';import assert from'node:assert/strict';import{Client}from'pg';
import{getPrismaClient,resetClientPool}from'./src/database/prisma';import{putObject}from'./src/storage';import{getBoss,ensureQueues,QUEUE_VALIDATE,QUEUE_COMMIT}from'./src/jobs/queue';import{sweepDispatches}from'./src/jobs/dispatcher';
const T='/tmp/gate02-review5-20260926-siq330x3',a=JSON.parse(readFileSync(T+'/actors-private.json','utf8')),db=getPrismaClient(),pg=new Client({connectionString:process.env.DATABASE_URL}),out:any={checks:[],observations:{}};let worker:any;
async function check(name:string,expected:any,fn:()=>Promise<any>){let actual;try{actual=await fn();assert.deepEqual(actual,expected);out.checks.push({name,expected,actual,status:'PASS'})}catch(e:any){out.checks.push({name,expected,actual,status:'FAIL',error:e.message?.slice(0,600)})}console.log(name,out.checks.at(-1).status);writeFileSync(T+'/evidence/worker-assertions.json',JSON.stringify(out,null,2));}
async function member(role:string,status='active'){const id=randomUUID(),authId='auth-'+id,email=id+'@example.test';await db.authUser.create({data:{id:authId,email,name:'synthetic'}});await db.user.create({data:{id,authUserId:authId,email,displayName:'worker test',status:status as any}});await db.membership.create({data:{orgId:a.owner.orgId,userId:id,role:role as any}});return id}
async function task(userId:string,mode='normal',storeId=a.storeId,sourceId=a.sourceId){const id=randomUUID();const text=readFileSync('tests/fixtures/golden/store-a/products.csv','utf8').replaceAll('XM-DEMO-A','G2-STORE').replace('P1','P'+id.slice(0,7));let raw='raw/'+id+'/source.csv';if(mode==='directory'){raw='raw/'+id;mkdirSync(T+'/private/'+raw,{recursive:true})}else if(mode!=='missing')await putObject(raw,Readable.from([mode==='badtime'?text.replaceAll('2026-09-11T09:00:00+08:00','2026-09-11T09:00:00+24:00'):mode==='badheader'?'wrong\nvalue':text]));return db.importTask.create({data:{id,orgId:a.owner.orgId,storeId,dataSourceId:sourceId,sourceKind:'products',createdBy:userId,originalFilename:'w.csv',rawObjectKey:raw,fileSha256:createHash('sha256').update(id).digest('hex'),uploadRequestKey:id,baseDatasetVersion:0n,outboxStatus:'pending',rowCount:2,updatedAt:new Date(Date.now()-120000)}})}
async function waitTask(id:string,pred:(x:any)=>boolean){for(let i=0;i<180;i++){const x=await db.importTask.findUniqueOrThrow({where:{id}});if(pred(x))return x;await new Promise(r=>setTimeout(r,100))}return db.importTask.findUniqueOrThrow({where:{id}})}
async function main(){await pg.connect();const boss=await getBoss();await ensureQueues(boss);await pg.query("UPDATE pgboss.job SET state='cancelled' WHERE state IN ('created','retry')");const disabled=await member('operator'),global=await member('operator','disabled'),downgraded=await member('operator');const normal=await task(a.owner.userId),revoked=await task(disabled),glob=await task(global),down=await task(downgraded),missing=await task(a.owner.userId,'missing'),badheader=await task(a.owner.userId,'badheader'),badtime=await task(a.owner.userId,'badtime'),dir=await task(a.owner.userId,'directory');await db.membership.updateMany({where:{userId:disabled},data:{status:'disabled'}});await db.membership.updateMany({where:{userId:downgraded},data:{role:'customer_service'}});
const archStore=await db.store.create({data:{orgId:a.owner.orgId,name:'arch-worker',externalStoreId:'G2-STORE-W',platform:'manual',currency:'CNY',timezone:'UTC',status:'archived'}});const archSource=await db.dataSource.create({data:{orgId:a.owner.orgId,storeId:archStore.id,name:'arch-source',sourceNamespace:'arch',adapterKind:'csv'}});const archived=await task(a.owner.userId,'normal',archStore.id,archSource.id);
for(const t of[normal,revoked,glob,down,missing,badheader,badtime,dir,archived]){await boss.send(QUEUE_VALIDATE,{taskId:t.id},{retryLimit:1,retryDelay:1});await db.importTask.update({where:{id:t.id},data:{outboxStatus:'dispatched'}})}
const log=openSync(T+'/evidence/worker-built.log','w');worker=spawn(process.execPath,['dist/jobs/worker.js'],{env:process.env,stdio:['ignore',log,log]});writeFileSync(T+'/worker.pid',String(worker.pid));
await check('H08 built Worker normal parse',['preview_ready',2,0],async()=>{const r=await waitTask(normal.id,x=>x.status!=='uploaded'&&x.status!=='validating');return[r.status,r.validCount,r.errorCount]});
await check('H05 disabled Membership rejected',['failed','UPLOAD_PERMISSION_REVOKED',0],async()=>{const r=await waitTask(revoked.id,x=>x.status==='failed');return[r.status,r.errorCode,r.validCount]});
await check('H05 downgrade rejected',['failed','UPLOAD_PERMISSION_REVOKED',0],async()=>{const r=await waitTask(down.id,x=>x.status==='failed');return[r.status,r.errorCode,r.validCount]});
await check('H05 disabled global user rejected',['failed','UPLOAD_PERMISSION_REVOKED',0],async()=>{const r=await waitTask(glob.id,x=>x.status!=='uploaded'&&x.status!=='validating');return[r.status,r.errorCode,r.validCount]});
await check('H08 missing source terminal',['failed','SOURCE_FILE_MISSING'],async()=>{const r=await waitTask(missing.id,x=>x.status==='failed');return[r.status,r.errorCode]});
await check('H08 malformed header private errors',['failed','MISSING_COLUMN',true],async()=>{const r=await waitTask(badheader.id,x=>x.status==='failed');return[r.status,r.errorCode,!!r.errorObjectKey&&r.errorObjectKey.startsWith('errors/')]});
await check('H08 terminal replay keeps preview version',true,async()=>{const before=await db.importTask.findUniqueOrThrow({where:{id:normal.id}});await boss.send(QUEUE_VALIDATE,{taskId:normal.id});await new Promise(r=>setTimeout(r,3000));const after=await db.importTask.findUniqueOrThrow({where:{id:normal.id}});return before.previewVersion===after.previewVersion&&after.status==='preview_ready'});
const lost=await task(a.owner.userId);await check('H08 dispatcher lost dispatch reaches ready',true,async()=>{const sweep=await sweepDispatches();const r=await waitTask(lost.id,x=>x.status==='preview_ready');return sweep.dispatched>=1&&r.status==='preview_ready'});
const stuck=await task(a.owner.userId);await db.importTask.update({where:{id:stuck.id},data:{status:'validating',outboxStatus:'dispatched',updatedAt:new Date(Date.now()-11*60000)}});await check('H08 interrupted validation finalizes',['failed','VALIDATE_INTERRUPTED'],async()=>{await sweepDispatches();const r=await db.importTask.findUniqueOrThrow({where:{id:stuck.id}});return[r.status,r.errorCode]});
await new Promise(r=>setTimeout(r,5000));for(const[n,t]of Object.entries({badtime,dir,archived})){const task=await db.importTask.findUniqueOrThrow({where:{id:t.id}});const jobs=(await pg.query('SELECT name,state,retry_count,retry_limit,output FROM pgboss.job WHERE data->>\'taskId\'=$1',[t.id])).rows;out.observations[n]={id:t.id,status:task.status,errorCode:task.errorCode,valid:task.validCount,errors:task.errorCount,jobs};}
await check('H03 invalid offset reaches row error without worker crash',['preview_ready',0,2],async()=>{const r=await db.importTask.findUniqueOrThrow({where:{id:badtime.id}});return [r.status,r.validCount,r.errorCount]});
await check('H08 retry exhausted immediately finalizes task',true,async()=>{const r=await db.importTask.findUniqueOrThrow({where:{id:dir.id}});return r.status==='failed'&&r.errorCode==='VALIDATE_FAILED'});
await boss.send(QUEUE_COMMIT,{taskId:normal.id},{retryLimit:0});await new Promise(r=>setTimeout(r,3000));await check('commit explicitly refused no fact writes',true,async()=>{const q=(await pg.query('SELECT state FROM pgboss.job WHERE name=$1 AND data->>\'taskId\'=$2',[QUEUE_COMMIT,normal.id])).rows;return q.some(x=>x.state==='failed')&&(await db.product.count({where:{orgId:a.owner.orgId}}))===0});
writeFileSync(T+'/evidence/worker-assertions.json',JSON.stringify(out,null,2));
}
main().catch(e=>{console.error(e);process.exitCode=2}).finally(async()=>{worker?.kill('SIGTERM');await(new Promise(r=>setTimeout(r,300)));await(await getBoss()).stop();await db.$disconnect();await resetClientPool();await pg.end();process.exit(process.exitCode===2?2:out.checks.some((x:any)=>x.status==='FAIL')?1:0)});
